// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBGC_9MwZWz7hpfwSWjmnu_f2iDuL13-uE',
    appId: '1:594961400985:web:3ba907bf0926f6899f2408',
    messagingSenderId: '594961400985',
    projectId: 'market-management-f703d',
    authDomain: 'market-management-f703d.firebaseapp.com',
    databaseURL: 'https://market-management-f703d-default-rtdb.firebaseio.com',
    storageBucket: 'market-management-f703d.firebasestorage.app',
    measurementId: 'G-GL3VSHR0HN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA9Rh-8y5OPa46mVXd2ZAt05wcAm3Nkf8U',
    appId: '1:594961400985:android:b363b2503c0213909f2408',
    messagingSenderId: '594961400985',
    projectId: 'market-management-f703d',
    databaseURL: 'https://market-management-f703d-default-rtdb.firebaseio.com',
    storageBucket: 'market-management-f703d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDewsz2T8GvnxrSQK1CviBSAOcRT-xzjK8',
    appId: '1:594961400985:ios:a23eb755d440e9669f2408',
    messagingSenderId: '594961400985',
    projectId: 'market-management-f703d',
    databaseURL: 'https://market-management-f703d-default-rtdb.firebaseio.com',
    storageBucket: 'market-management-f703d.firebasestorage.app',
    iosBundleId: 'com.example.marketManagement',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDewsz2T8GvnxrSQK1CviBSAOcRT-xzjK8',
    appId: '1:594961400985:ios:a23eb755d440e9669f2408',
    messagingSenderId: '594961400985',
    projectId: 'market-management-f703d',
    databaseURL: 'https://market-management-f703d-default-rtdb.firebaseio.com',
    storageBucket: 'market-management-f703d.firebasestorage.app',
    iosBundleId: 'com.example.marketManagement',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBGC_9MwZWz7hpfwSWjmnu_f2iDuL13-uE',
    appId: '1:594961400985:web:140de2ce528dffc49f2408',
    messagingSenderId: '594961400985',
    projectId: 'market-management-f703d',
    authDomain: 'market-management-f703d.firebaseapp.com',
    databaseURL: 'https://market-management-f703d-default-rtdb.firebaseio.com',
    storageBucket: 'market-management-f703d.firebasestorage.app',
    measurementId: 'G-ELR9MN7TCZ',
  );
}
